// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhcILz7L82LFJFQJesto0uHONxM1TwSnE',
    appId: '1:306493471644:web:ff7168ffe64efa8c516659',
    messagingSenderId: '306493471644',
    projectId: 'chat-app-57800',
    authDomain: 'chat-app-57800.firebaseapp.com',
    storageBucket: 'chat-app-57800.appspot.com',
    measurementId: 'G-PRL21SF52W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHhwIH5ij_kKvJ629sn0dzVgtoUJKM-fQ',
    appId: '1:306493471644:android:3b616a773bfc7c92516659',
    messagingSenderId: '306493471644',
    projectId: 'chat-app-57800',
    storageBucket: 'chat-app-57800.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChJAXenhnel-tzIrXmiuY86_uhrI-gfaY',
    appId: '1:306493471644:ios:16727b2fc95826d3516659',
    messagingSenderId: '306493471644',
    projectId: 'chat-app-57800',
    storageBucket: 'chat-app-57800.appspot.com',
    iosClientId: '306493471644-ap687gvd0kroc00dg9h9j1if0jv1gn71.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChJAXenhnel-tzIrXmiuY86_uhrI-gfaY',
    appId: '1:306493471644:ios:16727b2fc95826d3516659',
    messagingSenderId: '306493471644',
    projectId: 'chat-app-57800',
    storageBucket: 'chat-app-57800.appspot.com',
    iosClientId: '306493471644-ap687gvd0kroc00dg9h9j1if0jv1gn71.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
